### ISSUE TITLE
Decoder in D-linear model

### ISSUE THREAD

**Issue by wtestererer** [cure-lab/DLinear#1]
hi could you please explain the usage of the decoder in the model for it's initialized but never been called? thanks

**Comment by wtestererer** [comment]
also the configs when implementing d-linear contain an arg "label length", i noticed that it's from informer for its decoder start token, so how does this setting actually help in d-linear model? thanks

**Comment by mixiancmx** [comment]
Hi,
This is a leftover problem from the previous experiment. We tried to add a decoder layer but found that it had little impact on the results. Then we just commented out the use of the decoder layer. All the experiment in the paper is done with the decoder layer initialized but never been called. In order to make the result exactly the same as we report in the paper, we keep it in the code. You can remove the initialization of decoder in DLinear, and the results might be very slightly different.


> hi could you please explain the usage of the decoder in the model for it's initialized but never been called? thanks

**Comment by mixiancmx** [comment]
> also the configs when implementing d-linear contain an arg "label length", i noticed that it's from informer for its decoder start token, so how does this setting actually help in d-linear model? thanks

"label length" is used for the decoder of transformer based methods, i.e. Autoformer, Informer. DLinear doesn't use "label length". DLinear and transformer based methods use the same dataloader. The "label length" should be lower than "seq length", otherwise the dataloader cannot work.
